apiVersion: v1
kind: Service
metadata:
  name: mysql-product
  namespace: projeto-final
  labels:
    app: mysql-product
    component: database
    service: product
spec:
  clusterIP: None
  selector:
    app: mysql-product
  ports:
  - port: 3306
    targetPort: mysql-prd-port #it isn't a interdependent variable, abstration case caused by the creation the port name in the statefulset
    name: mysql-product-port