apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: projeto-final
type: Opaque
stringData:
  
  MYSQL_ROOT_PASSWORD: "RootPassword123!"
  
  USER_DB_PASSWORD: "UserDbPassword123!"     

  PRODUCT_DB_PASSWORD: "ProductDbPassword123!" 

  SECRET_KEY: "YourAppSecretKey123!"