apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: projeto-final
  labels:
    app: user-service
    component: backend
    service: user
spec:
  selector:
    app: user-service
  ports:
  - port: 5001 #exposed service port
    targetPort: 5001 #internal container port
    name: http
    protocol: TCP
  type: ClusterIP #only visible within the cluster
